// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type BlendMode int8

const (
	BlendModeNormal      BlendMode = 0
	BlendModeDestAtop    BlendMode = 1
	BlendModeClear       BlendMode = 2
	BlendModeSource      BlendMode = 3
	BlendModeDarken      BlendMode = 4
	BlendModeMultiply    BlendMode = 5
	BlendModeColorBurn   BlendMode = 6
	BlendModeLighten     BlendMode = 7
	BlendModeScreen      BlendMode = 8
	BlendModeColorDodge  BlendMode = 9
	BlendModeOverlay     BlendMode = 10
	BlendModeSoftLight   BlendMode = 11
	BlendModeHardLight   BlendMode = 12
	BlendModeDifference  BlendMode = 13
	BlendModeExclusion   BlendMode = 14
	BlendModeHue         BlendMode = 15
	BlendModeSaturation  BlendMode = 16
	BlendModeColor       BlendMode = 17
	BlendModeLuminosity  BlendMode = 18
	BlendModePlusDarker  BlendMode = 19
	BlendModePlusLighter BlendMode = 20
)

var EnumNamesBlendMode = map[BlendMode]string{
	BlendModeNormal:      "Normal",
	BlendModeDestAtop:    "DestAtop",
	BlendModeClear:       "Clear",
	BlendModeSource:      "Source",
	BlendModeDarken:      "Darken",
	BlendModeMultiply:    "Multiply",
	BlendModeColorBurn:   "ColorBurn",
	BlendModeLighten:     "Lighten",
	BlendModeScreen:      "Screen",
	BlendModeColorDodge:  "ColorDodge",
	BlendModeOverlay:     "Overlay",
	BlendModeSoftLight:   "SoftLight",
	BlendModeHardLight:   "HardLight",
	BlendModeDifference:  "Difference",
	BlendModeExclusion:   "Exclusion",
	BlendModeHue:         "Hue",
	BlendModeSaturation:  "Saturation",
	BlendModeColor:       "Color",
	BlendModeLuminosity:  "Luminosity",
	BlendModePlusDarker:  "PlusDarker",
	BlendModePlusLighter: "PlusLighter",
}

var EnumValuesBlendMode = map[string]BlendMode{
	"Normal":      BlendModeNormal,
	"DestAtop":    BlendModeDestAtop,
	"Clear":       BlendModeClear,
	"Source":      BlendModeSource,
	"Darken":      BlendModeDarken,
	"Multiply":    BlendModeMultiply,
	"ColorBurn":   BlendModeColorBurn,
	"Lighten":     BlendModeLighten,
	"Screen":      BlendModeScreen,
	"ColorDodge":  BlendModeColorDodge,
	"Overlay":     BlendModeOverlay,
	"SoftLight":   BlendModeSoftLight,
	"HardLight":   BlendModeHardLight,
	"Difference":  BlendModeDifference,
	"Exclusion":   BlendModeExclusion,
	"Hue":         BlendModeHue,
	"Saturation":  BlendModeSaturation,
	"Color":       BlendModeColor,
	"Luminosity":  BlendModeLuminosity,
	"PlusDarker":  BlendModePlusDarker,
	"PlusLighter": BlendModePlusLighter,
}

func (v BlendMode) String() string {
	if s, ok := EnumNamesBlendMode[v]; ok {
		return s
	}
	return "BlendMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
