// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CachedExtentComponent struct {
	_tab flatbuffers.Table
}

func GetRootAsCachedExtentComponent(buf []byte, offset flatbuffers.UOffsetT) *CachedExtentComponent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CachedExtentComponent{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCachedExtentComponent(buf []byte, offset flatbuffers.UOffsetT) *CachedExtentComponent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CachedExtentComponent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CachedExtentComponent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CachedExtentComponent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CachedExtentComponent) Rect(obj *Rect) *Rect {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Rect)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func CachedExtentComponentStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CachedExtentComponentAddRect(builder *flatbuffers.Builder, rect flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(rect), 0)
}
func CachedExtentComponentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
