// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DrawingContentText struct {
	_tab flatbuffers.Table
}

func GetRootAsDrawingContentText(buf []byte, offset flatbuffers.UOffsetT) *DrawingContentText {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DrawingContentText{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDrawingContentText(buf []byte, offset flatbuffers.UOffsetT) *DrawingContentText {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DrawingContentText{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DrawingContentText) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DrawingContentText) Table() flatbuffers.Table {
	return rcv._tab
}

func DrawingContentTextStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DrawingContentTextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
