// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DrawingContentImage struct {
	_tab flatbuffers.Table
}

func GetRootAsDrawingContentImage(buf []byte, offset flatbuffers.UOffsetT) *DrawingContentImage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DrawingContentImage{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDrawingContentImage(buf []byte, offset flatbuffers.UOffsetT) *DrawingContentImage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DrawingContentImage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DrawingContentImage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DrawingContentImage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DrawingContentImage) Image(obj *ImageDrawing) *ImageDrawing {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ImageDrawing)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DrawingContentImage) Tile() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DrawingContentImage) MutateTile(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func DrawingContentImageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DrawingContentImageAddImage(builder *flatbuffers.Builder, image flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(image), 0)
}
func DrawingContentImageAddTile(builder *flatbuffers.Builder, tile bool) {
	builder.PrependBoolSlot(1, tile, false)
}
func DrawingContentImageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
