// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DrawingContentAngularGradient struct {
	_tab flatbuffers.Table
}

func GetRootAsDrawingContentAngularGradient(buf []byte, offset flatbuffers.UOffsetT) *DrawingContentAngularGradient {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DrawingContentAngularGradient{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDrawingContentAngularGradient(buf []byte, offset flatbuffers.UOffsetT) *DrawingContentAngularGradient {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DrawingContentAngularGradient{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DrawingContentAngularGradient) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DrawingContentAngularGradient) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DrawingContentAngularGradient) Center(obj *Point) *Point {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Point)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DrawingContentAngularGradient) Angle() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DrawingContentAngularGradient) MutateAngle(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *DrawingContentAngularGradient) Locations(j int) float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetFloat32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *DrawingContentAngularGradient) LocationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DrawingContentAngularGradient) MutateLocations(j int, n float32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateFloat32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *DrawingContentAngularGradient) Colors(obj *RGBAColor, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 16
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DrawingContentAngularGradient) ColorsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DrawingContentAngularGradientStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func DrawingContentAngularGradientAddCenter(builder *flatbuffers.Builder, center flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(center), 0)
}
func DrawingContentAngularGradientAddAngle(builder *flatbuffers.Builder, angle float32) {
	builder.PrependFloat32Slot(1, angle, 0.0)
}
func DrawingContentAngularGradientAddLocations(builder *flatbuffers.Builder, locations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(locations), 0)
}
func DrawingContentAngularGradientStartLocationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DrawingContentAngularGradientAddColors(builder *flatbuffers.Builder, colors flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(colors), 0)
}
func DrawingContentAngularGradientStartColorsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(16, numElems, 4)
}
func DrawingContentAngularGradientEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
