// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type DrawingContent byte

const (
	DrawingContentNONE                          DrawingContent = 0
	DrawingContentDrawingContentColor           DrawingContent = 1
	DrawingContentDrawingContentLinearGradient  DrawingContent = 2
	DrawingContentDrawingContentAngularGradient DrawingContent = 3
	DrawingContentDrawingContentRadialGradient  DrawingContent = 4
	DrawingContentDrawingContentImage           DrawingContent = 5
	DrawingContentDrawingContentText            DrawingContent = 6
)

var EnumNamesDrawingContent = map[DrawingContent]string{
	DrawingContentNONE:                          "NONE",
	DrawingContentDrawingContentColor:           "DrawingContentColor",
	DrawingContentDrawingContentLinearGradient:  "DrawingContentLinearGradient",
	DrawingContentDrawingContentAngularGradient: "DrawingContentAngularGradient",
	DrawingContentDrawingContentRadialGradient:  "DrawingContentRadialGradient",
	DrawingContentDrawingContentImage:           "DrawingContentImage",
	DrawingContentDrawingContentText:            "DrawingContentText",
}

var EnumValuesDrawingContent = map[string]DrawingContent{
	"NONE":                          DrawingContentNONE,
	"DrawingContentColor":           DrawingContentDrawingContentColor,
	"DrawingContentLinearGradient":  DrawingContentDrawingContentLinearGradient,
	"DrawingContentAngularGradient": DrawingContentDrawingContentAngularGradient,
	"DrawingContentRadialGradient":  DrawingContentDrawingContentRadialGradient,
	"DrawingContentImage":           DrawingContentDrawingContentImage,
	"DrawingContentText":            DrawingContentDrawingContentText,
}

func (v DrawingContent) String() string {
	if s, ok := EnumNamesDrawingContent[v]; ok {
		return s
	}
	return "DrawingContent(" + strconv.FormatInt(int64(v), 10) + ")"
}
