// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type FillRule int8

const (
	FillRuleWinding FillRule = 0
	FillRuleEvenOdd FillRule = 1
)

var EnumNamesFillRule = map[FillRule]string{
	FillRuleWinding: "Winding",
	FillRuleEvenOdd: "EvenOdd",
}

var EnumValuesFillRule = map[string]FillRule{
	"Winding": FillRuleWinding,
	"EvenOdd": FillRuleEvenOdd,
}

func (v FillRule) String() string {
	if s, ok := EnumNamesFillRule[v]; ok {
		return s
	}
	return "FillRule(" + strconv.FormatInt(int64(v), 10) + ")"
}
