// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FilterShadow struct {
	_tab flatbuffers.Table
}

func GetRootAsFilterShadow(buf []byte, offset flatbuffers.UOffsetT) *FilterShadow {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FilterShadow{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFilterShadow(buf []byte, offset flatbuffers.UOffsetT) *FilterShadow {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FilterShadow{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FilterShadow) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FilterShadow) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FilterShadow) Shadow(obj *Shadow) *Shadow {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Shadow)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func FilterShadowStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FilterShadowAddShadow(builder *flatbuffers.Builder, shadow flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(shadow), 0)
}
func FilterShadowEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
