// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type Filter byte

const (
	FilterNONE                Filter = 0
	FilterFilterColorControls Filter = 1
	FilterFilterGaussianBlur  Filter = 2
	FilterFilterMotionBlur    Filter = 3
	FilterFilterZoomBlur      Filter = 4
	FilterFilterShadow        Filter = 5
)

var EnumNamesFilter = map[Filter]string{
	FilterNONE:                "NONE",
	FilterFilterColorControls: "FilterColorControls",
	FilterFilterGaussianBlur:  "FilterGaussianBlur",
	FilterFilterMotionBlur:    "FilterMotionBlur",
	FilterFilterZoomBlur:      "FilterZoomBlur",
	FilterFilterShadow:        "FilterShadow",
}

var EnumValuesFilter = map[string]Filter{
	"NONE":                FilterNONE,
	"FilterColorControls": FilterFilterColorControls,
	"FilterGaussianBlur":  FilterFilterGaussianBlur,
	"FilterMotionBlur":    FilterFilterMotionBlur,
	"FilterZoomBlur":      FilterFilterZoomBlur,
	"FilterShadow":        FilterFilterShadow,
}

func (v Filter) String() string {
	if s, ok := EnumNamesFilter[v]; ok {
		return s
	}
	return "Filter(" + strconv.FormatInt(int64(v), 10) + ")"
}
