// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type InterpolationQuality int8

const (
	InterpolationQualityDefault InterpolationQuality = 0
	InterpolationQualityNone    InterpolationQuality = 1
	InterpolationQualityLow     InterpolationQuality = 2
	InterpolationQualityMedium  InterpolationQuality = 3
	InterpolationQualityHigh    InterpolationQuality = 4
)

var EnumNamesInterpolationQuality = map[InterpolationQuality]string{
	InterpolationQualityDefault: "Default",
	InterpolationQualityNone:    "None",
	InterpolationQualityLow:     "Low",
	InterpolationQualityMedium:  "Medium",
	InterpolationQualityHigh:    "High",
}

var EnumValuesInterpolationQuality = map[string]InterpolationQuality{
	"Default": InterpolationQualityDefault,
	"None":    InterpolationQualityNone,
	"Low":     InterpolationQualityLow,
	"Medium":  InterpolationQualityMedium,
	"High":    InterpolationQualityHigh,
}

func (v InterpolationQuality) String() string {
	if s, ok := EnumNamesInterpolationQuality[v]; ok {
		return s
	}
	return "InterpolationQuality(" + strconv.FormatInt(int64(v), 10) + ")"
}
