// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type LineCap int8

const (
	LineCapButt   LineCap = 0
	LineCapRound  LineCap = 1
	LineCapSquare LineCap = 2
)

var EnumNamesLineCap = map[LineCap]string{
	LineCapButt:   "Butt",
	LineCapRound:  "Round",
	LineCapSquare: "Square",
}

var EnumValuesLineCap = map[string]LineCap{
	"Butt":   LineCapButt,
	"Round":  LineCapRound,
	"Square": LineCapSquare,
}

func (v LineCap) String() string {
	if s, ok := EnumNamesLineCap[v]; ok {
		return s
	}
	return "LineCap(" + strconv.FormatInt(int64(v), 10) + ")"
}
