// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type LineJoin int8

const (
	LineJoinMiter LineJoin = 0
	LineJoinRound LineJoin = 1
	LineJoinBevel LineJoin = 2
)

var EnumNamesLineJoin = map[LineJoin]string{
	LineJoinMiter: "Miter",
	LineJoinRound: "Round",
	LineJoinBevel: "Bevel",
}

var EnumValuesLineJoin = map[string]LineJoin{
	"Miter": LineJoinMiter,
	"Round": LineJoinRound,
	"Bevel": LineJoinBevel,
}

func (v LineJoin) String() string {
	if s, ok := EnumNamesLineJoin[v]; ok {
		return s
	}
	return "LineJoin(" + strconv.FormatInt(int64(v), 10) + ")"
}
