// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type MaskComponentMode int8

const (
	MaskComponentModeNode     MaskComponentMode = 0
	MaskComponentModeClip     MaskComponentMode = 1
	MaskComponentModeKnockout MaskComponentMode = 2
)

var EnumNamesMaskComponentMode = map[MaskComponentMode]string{
	MaskComponentModeNode:     "Node",
	MaskComponentModeClip:     "Clip",
	MaskComponentModeKnockout: "Knockout",
}

var EnumValuesMaskComponentMode = map[string]MaskComponentMode{
	"Node":     MaskComponentModeNode,
	"Clip":     MaskComponentModeClip,
	"Knockout": MaskComponentModeKnockout,
}

func (v MaskComponentMode) String() string {
	if s, ok := EnumNamesMaskComponentMode[v]; ok {
		return s
	}
	return "MaskComponentMode(" + strconv.FormatInt(int64(v), 10) + ")"
}
