// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type PathOperation int8

const (
	PathOperationMoveTo  PathOperation = 0
	PathOperationLineTo  PathOperation = 1
	PathOperationQuadTo  PathOperation = 2
	PathOperationCubicTo PathOperation = 3
	PathOperationClose   PathOperation = 4
)

var EnumNamesPathOperation = map[PathOperation]string{
	PathOperationMoveTo:  "MoveTo",
	PathOperationLineTo:  "LineTo",
	PathOperationQuadTo:  "QuadTo",
	PathOperationCubicTo: "CubicTo",
	PathOperationClose:   "Close",
}

var EnumValuesPathOperation = map[string]PathOperation{
	"MoveTo":  PathOperationMoveTo,
	"LineTo":  PathOperationLineTo,
	"QuadTo":  PathOperationQuadTo,
	"CubicTo": PathOperationCubicTo,
	"Close":   PathOperationClose,
}

func (v PathOperation) String() string {
	if s, ok := EnumNamesPathOperation[v]; ok {
		return s
	}
	return "PathOperation(" + strconv.FormatInt(int64(v), 10) + ")"
}
