// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Rect struct {
	_tab flatbuffers.Struct
}

func (rcv *Rect) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Rect) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Rect) Origin(obj *Point) *Point {
	if obj == nil {
		obj = new(Point)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+0)
	return obj
}
func (rcv *Rect) Size(obj *Size) *Size {
	if obj == nil {
		obj = new(Size)
	}
	obj.Init(rcv._tab.Bytes, rcv._tab.Pos+8)
	return obj
}

func CreateRect(builder *flatbuffers.Builder, origin_x float32, origin_y float32, size_width float32, size_height float32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.Prep(4, 8)
	builder.PrependFloat32(size_height)
	builder.PrependFloat32(size_width)
	builder.Prep(4, 8)
	builder.PrependFloat32(origin_y)
	builder.PrependFloat32(origin_x)
	return builder.Offset()
}
