// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RGBAColor struct {
	_tab flatbuffers.Struct
}

func (rcv *RGBAColor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RGBAColor) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *RGBAColor) R() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *RGBAColor) MutateR(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *RGBAColor) G() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *RGBAColor) MutateG(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *RGBAColor) B() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *RGBAColor) MutateB(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *RGBAColor) A() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *RGBAColor) MutateA(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func CreateRGBAColor(builder *flatbuffers.Builder, r float32, g float32, b float32, a float32) flatbuffers.UOffsetT {
	builder.Prep(4, 16)
	builder.PrependFloat32(a)
	builder.PrependFloat32(b)
	builder.PrependFloat32(g)
	builder.PrependFloat32(r)
	return builder.Offset()
}
