// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import "strconv"

type Shape byte

const (
	ShapeNONE         Shape = 0
	ShapeShapePath    Shape = 1
	ShapeShapeRect    Shape = 2
	ShapeShapeEllipse Shape = 3
)

var EnumNamesShape = map[Shape]string{
	ShapeNONE:         "NONE",
	ShapeShapePath:    "ShapePath",
	ShapeShapeRect:    "ShapeRect",
	ShapeShapeEllipse: "ShapeEllipse",
}

var EnumValuesShape = map[string]Shape{
	"NONE":         ShapeNONE,
	"ShapePath":    ShapeShapePath,
	"ShapeRect":    ShapeShapeRect,
	"ShapeEllipse": ShapeShapeEllipse,
}

func (v Shape) String() string {
	if s, ok := EnumNamesShape[v]; ok {
		return s
	}
	return "Shape(" + strconv.FormatInt(int64(v), 10) + ")"
}
