// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Size struct {
	_tab flatbuffers.Struct
}

func (rcv *Size) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Size) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Size) Width() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Size) MutateWidth(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Size) Height() float32 {
	return rcv._tab.GetFloat32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Size) MutateHeight(n float32) bool {
	return rcv._tab.MutateFloat32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateSize(builder *flatbuffers.Builder, width float32, height float32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependFloat32(height)
	builder.PrependFloat32(width)
	return builder.Offset()
}
