// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package FBPRFileMarina

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TransformComponent struct {
	_tab flatbuffers.Table
}

func GetRootAsTransformComponent(buf []byte, offset flatbuffers.UOffsetT) *TransformComponent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TransformComponent{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTransformComponent(buf []byte, offset flatbuffers.UOffsetT) *TransformComponent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TransformComponent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TransformComponent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TransformComponent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TransformComponent) Matrix(obj *Matrix) *Matrix {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(Matrix)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func TransformComponentStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TransformComponentAddMatrix(builder *flatbuffers.Builder, matrix flatbuffers.UOffsetT) {
	builder.PrependStructSlot(0, flatbuffers.UOffsetT(matrix), 0)
}
func TransformComponentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
